### ISSUE TITLE
Ordenar por fecha o ID de forma DESC para visualizar el ultimo producto, primero

### ISSUE THREAD

**Issue by ivanfretes** [josego85/products-covid19py#11]

**Comment by josego85** [comment]
> 
> 
> _No description provided._
Pero donde? Porque en el filtro no se si como consumidor te va a importar filtrar el último producto.
En una sección aparte podria ser?

**Comment by ivanfretes** [comment]
Tenes razon, asocie a disponibilidad y stock!

**Comment by ivanfretes** [comment]
V
